first test
elefus/bad_java_202107 pull request #1
Opened 2021-08-06 14:44 UTC by MyPlaceMNOGOCIFR

2021-08-08 19:02 UTC, elefus requested changes

2021-08-08 19:02 UTC, elefus commented on src/com/bad_java/homework/hyperskill/chat_bot/part_5/SimpleBot.java
> +      System.out.printf("%d!\n", i);
Лучше использовать %n вместо \n
Первый вариант будет учитывать ОС в которой осуществляется запуск и использовать её перенос строки

2021-08-09 14:36 UTC, MyPlaceMNOGOCIFR commented on src/com/bad_java/homework/hyperskill/chat_bot/part_5/SimpleBot.java
> +          isEnd = true;
Ошибся. Исправил.

2021-08-09 14:38 UTC, MyPlaceMNOGOCIFR commented on src/com/bad_java/homework/hyperskill/chat_bot/part_5/SimpleBot.java
> +      System.out.printf("%d!\n", i);
Не знал) переделал

2021-08-16 19:17 UTC, closed without merging