Add SimpleChattyBot_Kislitsyn
elefus/bad_java_202107 pull request #10
Opened 2021-08-08 17:02 UTC by KislitsynILYA

2021-08-09 12:02 UTC, elefus requested changes

2021-08-09 12:02 UTC, elefus commented on src/com/bad_java/homework/hyperskill/chat_bot/SimpleChattyBot_Kislitsyn.java
> +            System.out.printf("%d!\n", i);
Лучше использовать %n вместо \n
Первый вариант будет учитывать ОС в которой осуществляется запуск и использовать её перенос строки

2021-08-09 12:02 UTC, elefus commented on src/com/bad_java/homework/hyperskill/chat_bot/SimpleChattyBot_Kislitsyn.java
> +            else
Codestyle violation

2021-08-09 12:02 UTC, elefus commented on src/com/bad_java/homework/hyperskill/chat_bot/SimpleChattyBot_Kislitsyn.java
> +                break;
Зачем использовать while(true) + break, если есть вполне конкретное условие остановки, которое можно проверять для остановки цикла?

2021-08-09 16:13 UTC, KislitsynILYA commented on src/com/bad_java/homework/hyperskill/chat_bot/SimpleChattyBot_Kislitsyn.java
> +                break;
То есть надо было использовать что то такое:

2021-08-13 11:30 UTC, KislitsynILYA commented on src/com/bad_java/homework/hyperskill/coffee_machine/Keep_Track_Of_The_Supplies_Part_5.java
> +}
Решал процедурным способом, так как hyperskill не просил ООП, но в 6 part'e изучается классы и enum'ы, поэтому позже переделаю на лад ООП

2021-08-18 08:50 UTC, elefus requested changes
Много отступлений от Google Java-styleguide, посмотри на него еще разок и настрой в IDEA

2021-08-18 08:50 UTC, elefus commented on src/com/bad_java/homework/hyperskill/coffee_machine/Keep_Track_Of_The_Supplies_Part_5.java
> +public class Keep_Track_Of_The_Supplies_Part_5 {
Во всех Java-styleguide рекомендуется использовать CamelCase а не Snake_Case

2021-08-18 08:50 UTC, elefus commented on src/com/bad_java/homework/hyperskill/coffee_machine/Keep_Track_Of_The_Supplies_Part_5.java
> +    public static void MakingCoffee() {
По Google Java-styleguide имена методов идут с маленькой буквы в camelCase

2021-08-18 08:50 UTC, elefus commented on src/com/bad_java/homework/hyperskill/coffee_machine/Keep_Track_Of_The_Supplies_Part_5.java
> +        while(cheaker){
Можно использовать while(true) и в `case exit:` использовать return

2021-09-06 06:46 UTC, elefus approved these changes

2021-09-06 06:46 UTC, elefus commented on src/com/bad_java/homework/hyperskill/coffee_machine/CoffeeMachinePart6.java
> +  public void espressoMethod() {
Писать в названии метода слово "Method" избыточно =)
Можно использовать что-то вроде "makeEspresso" или "createEspresso"

2021-09-06 06:46 UTC, elefus commented on src/com/bad_java/homework/hyperskill/coffee_machine/CoffeeMachinePart6.java
> +      this.water_machine -= 250;
Явное использование this имеет смысл, если идет перекрытие областей видимости переменных.
В противном случае, его можно опустить.

2021-09-06 06:46 UTC, elefus commented on src/com/bad_java/homework/hyperskill/coffee_machine/CoffeeMachinePart6.java
> +      System.out.println("Sorry, not enough water!");
Стоит добавить выход из метода, после вывода сообщения.
Иначе получается, что сообщил о недостатке воды и пошел готовить дальше)

2021-09-06 06:47 UTC, merged