Simplebot 1-3 stages
elefus/bad_java_202107 pull request #11
Opened 2021-08-08 20:32 UTC by AksyonovaKaterina

2021-08-09 12:07 UTC, elefus requested changes

2021-08-09 12:07 UTC, elefus commented on src/com/bad_java/homework/hyperskill/chat_bot/part_1/SimpleBot.java
> +        public User registerUser() {
Codestyle violation - поплыли отступы

2021-08-09 12:07 UTC, elefus commented on src/com/bad_java/homework/hyperskill/chat_bot/part_1/SimpleBot.java
> +            System.out.printf("Hello! My name is %s.\n", NAME);
Лучше использовать %n вместо \n
Первый вариант будет учитывать ОС в которой осуществляется запуск и использовать её перенос строки

2021-08-09 12:58 UTC, AksyonovaKaterina commented on src/com/bad_java/homework/hyperskill/chat_bot/part_1/SimpleBot.java
> +        public User registerUser() {
Исправила

2021-08-09 12:58 UTC, AksyonovaKaterina commented on src/com/bad_java/homework/hyperskill/chat_bot/part_1/SimpleBot.java
> +        public static void sayDateOfBirthday () {
Исправила

2021-08-09 12:59 UTC, AksyonovaKaterina commented on src/com/bad_java/homework/hyperskill/chat_bot/part_1/SimpleBot.java
> +            System.out.printf("Hello! My name is %s.\n", NAME);
Спасибо, видимо упустила этот момент.
Исправила

2021-08-18 08:50 UTC, elefus approved these changes

2021-08-18 08:50 UTC, merged